ot chat gpt last one:


trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildVariant: 'dev' # Set your build variant
  buildVariantCapitalized: 'Dev' # Capitalized version of the build variant for Gradle tasks

steps:
  # Debugging step to print variables
  - script: |
      echo "Build Variant: $(buildVariant)"
      echo "Capitalized Build Variant: $(buildVariantCapitalized)"
    displayName: Print Variables

  # Set up Java 17 manually
  - script: |
      sudo apt-get update
      sudo apt-get install -y openjdk-17-jdk
      java -version
    displayName: Set up Java 17

  # Checkout the repository
  - task: Checkout@1
    displayName: Checkout source code

  # Download the correct google-services.json file
  - task: DownloadSecureFile@1
    name: DownloadGoogleServices
    displayName: Download google-services.json
    inputs:
      secureFile: google-services-$(buildVariant).json

  # Move google-services.json to app directory
  - script: |
      mv $(Agent.TempDirectory)/google-services-*.json $(System.DefaultWorkingDirectory)/app/google-services.json
    displayName: Move google-services.json to app directory

  # Build APK
  - script: |
      ./gradlew assemble$(buildVariantCapitalized)Debug
    displayName: Build APK

  # Upload APK to Firebase
  - script: |
      ./gradlew appDistributionUpload$(buildVariantCapitalized)Debug
    displayName: Upload APK to Firebase
