trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: buildVariant
    value: 'dev' # Change to 'prod' or 'qa' as needed
  - name: buildVariantCapitalized
    value: 'Dev' # Manually capitalize to match Gradle tasks

jobs:
  - job: BuildAndUpload
    displayName: Build and Upload APK to Firebase
    steps:
      - checkout: self

      - task: DownloadSecureFile@1
        displayName: Download google-services.json for Dev
        condition: eq(variables['buildVariant'], 'dev')
        inputs:
          secureFile: 'google-services-dev.json'

      - task: DownloadSecureFile@1
        displayName: Download google-services.json for Prod
        condition: eq(variables['buildVariant'], 'prod')
        inputs:
          secureFile: 'google-services-prod.json'

      - task: DownloadSecureFile@1
        displayName: Download google-services.json for QA
        condition: eq(variables['buildVariant'], 'qa')
        inputs:
          secureFile: 'google-services-qa.json'

      - script: |
          mv $(Agent.TempDirectory)/google-services.json $(System.DefaultWorkingDirectory)/app/google-services.json
        displayName: Move google-services.json to app directory

      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.x'
          addToPath: true

      - script: |
          ./gradlew assemble$(buildVariantCapitalized)Debug
        displayName: Build APK

      - script: |
          ./gradlew appDistributionUpload$(buildVariantCapitalized)Debug
        displayName: Upload APK to Firebase
